name: Go CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install dependencies
      run: go mod download

    - name: Build
      run: go build -v

    - name: Test
      run: go test -v ./...

    - name: Deploy (replace with your deployment steps)
      run: |
        echo "Deploying your Golang application..."
